### ISSUE TITLE
bad argument to 'path' error in multi-folder workspace

### ISSUE THREAD

**Issue by loneguardian** [JanSharp/SumnekoLuaPluginDevEnv#1]
Was redicted from (https://github.com/sumneko/lua-language-server/issues/1712). I was told that this is a plugin issue.

### How are you using the lua-language-server?

Visual Studio Code Extension (sumneko.lua)

### Which OS are you using?

Windows

### Expected Behaviour

When vscode is started and a lua file is opened, it shouldn't give a "nil path" error.

### Actual Behaviour

The following error is thrown when vscode is first started and a lua file is opened:
```
...o error report\test workspace\C\B\.vscode\lua\plugin.lua:24: bad argument #1 to 'path' (bee::path expected, got nil)
stack traceback:
	[C]: in function 'bee.filesystem.path'
	...o error report\test workspace\C\B\.vscode\lua\plugin.lua:24: in main chunk
	[C]: in function 'xpcall'
	script\plugin.lua:119: in function <script\plugin.lua:76>
[Error - 1:53:08 pm] An error occurred in the plugin, please report it to the plugin author.
Please check the details in the output or log.
Plugin path: C:\Users\User\Desktop\sumneko error report\test workspace\C\B\.vscode\lua\plugin.lua
```
However, I have not noticed any diminished function of the language server despite that error being thrown.

### Reproduction steps

1. Download this [test workspace setup](https://github.com/sumneko/lua-language-server/files/10046194/test.workspace.zip) that can reproduce the error.
2. Open the test workspace, choose either folder A or B and select the `test.lua` file.
3. Error should occur.

### Additional Notes

- The error does not happen if you reorder the folder by rearranging B before A.
- I have noticed that for this workspace, logs showed that the order of builtin library init does not follow the order of `folders` setting in the workspace file. Probably due to the path of B being special? When B is placed at the same level as A (instead of inside C), the builtin library init order does change according to the order in `folders` setting.

### Log File

[error.log](https://github.com/sumneko/lua-language-server/files/10046205/error.log)

**Comment by JanSharp** [comment]
(For the record, this is actually an issue with https://github.com/JanSharp/FactorioSumnekoLuaPlugin).

Aside from that, thanks for the repord and reproduction steps, it's now fixed and you can update the plugin

**Comment by loneguardian** [comment]
Thanks for the quick response.

Sorry for the mispost, I am really not familiar with the architecture of the language server and plugins. I was confused too when I couldn't find the familiar folder structure in this repo.

Did the quick check and the issue is no longer there.

**Comment by JanSharp** [comment]
No worries about the mispost, since you included the test workspace it didn't cost me any time.

Glad to hear that it works for you :)
